name: ci-docker

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: 'SGDK version'
        required: true
        default: '2.11'

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    environment: DockerHub
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Load environment variables from selected file
        run: |
          echo "Using version: ${{ github.event.inputs.target_version }}"
          echo "SGDK_RELEASE=${{ github.event.inputs.target_version }}" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "DOCKERHUB_REPONAME=docker-sgdk" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPONAME }}
          provider: dockerhub
          short_description: 'A Docker Image for SGDK Development'
          readme_file: 'README.md'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          build-args: |
            SGDK_RELEASE=${{ env.SGDK_RELEASE }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.TAG_NAME }}